title: Simplifying Reliability
email: pedrohso90@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Simple is elegant.
url: https://pedrohso90.github.io # the base hostname & protocol for your site, e.g. http://example.com
github_username:  pedrohso90
theme: minima
plugins:
  - jekyll-feed
